version: "3.9"
services:
  # Main app - pytrade
  pytrade:
    container_name: pytrade
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
    #restart: on-failure
    links:
      - rabbit
    networks:
      - pytrade

  # Rabbit for exchange between systems
  rabbit:
    container_name: pytrade-rabbit
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
      # Stomp
      - '15674:15674'
      - '61613:61613'

    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbit", "5672" ]
      #test: rabbitmq-diagnostic -q ping
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - pytrade

  # React web ui for basic management
  www:
    container_name: pytrade-www
    depends_on:
      pytrade:
        condition: service_started
    build:
      context: www
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # localhost:3000 in browser
    command: >
      bash -c "npm install && npm start --host 0.0.0.0 --port 3000 --live-reload -o"
    networks:
      - pytrade

# Network for exchange between systems
networks:
  pytrade:
    external: false