version: "3.9"
services:
  # Main app - pytrade
  pytrade:
#    profiles:
#      - pytrade
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    #restart: on-failure
    links:
      - rabbitmq
    networks:
      - pytrade

  # Rabbit for exchange between systems
  rabbitmq:
#    profiles:
#      - pytrade
#      - debug
#      - rabbit
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
      # Stomp
      - '15674:15674'

    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      #test: rabbitmq-diagnostic -q ping
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - pytrade

  # Angular web ui for basic management
  angular: #Web ui
#    profiles:
#      - pytrade
#      - debug
#      - angular
    container_name: pytrade-www  # Container name
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --live-reload -o"
    networks:
      - pytrade

# Network for exchange between systems
networks:
  pytrade:
    external: false